### ISSUE TITLE
app-scanner: Replace axios and http-proxy-agent with existing got and hpagent

### ISSUE THREAD

**Issue by binarymist** [purpleteam-labs/purpleteam#112]
In the app-scanner:

Remove dependencies: axios and http-proxy-agent. Both are used in app.emissary.js only.
Use existing dependencies got and hpagent in app.emissary.js instead.
There is an example of how got and hpagent is being used in zAp.js.
Do something similar, may not need to `extend` though.

**Comment by ShubhamPalriwala** [comment]
Hey, I looked into the code and I cannot see any use/dependency of either `axios` or `http-proxy-agent`? Do we use some other branch for development other than master?

**Comment by binarymist** [comment]
Hi @ShubhamPalriwala .

> Hey, I looked into the code and I cannot see any use/dependency of either axios or http-proxy-agent?

https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/main/src/api/app/models/app.emissary.js#L17-L18

> Do we use some other branch for development other than master?

There is no master

**Comment by ShubhamPalriwala** [comment]
Oh okay I didn't know we are having all our issues logged here! I'll start this working!!
