### ISSUE TITLE
Environment Variables aren't being read

### ISSUE THREAD

**Issue by ShubhamPalriwala** [purpleteam-labs/purpleteam#113]
### Actual Behavior:
![Screenshot_2022-02-14-02-20-31_1920x1080](https://user-images.githubusercontent.com/55556994/153830683-a5ba8434-ed96-4c3e-ad81-053d48913fb7.png)

It comes from [here](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/6d28344dfea0519ac4d961578ba07de785ed252c/config/config.js#L258) as:
```js
config.loadFile(path.join(__dirname, `config.${process.env.NODE_ENV}.json`));
```

...

### Expected Behavior:
The app should make use of the dotenv package and read the dotenv vars and replace the `config.undefined.json` accordingly!

...

### Steps to Reproduce:
1. Clone the repo and cd into it
2. Install deps using `npm i`
3. Replace ZAP API KEY  with your own and then run `npm start`
4. You should get the same error
...

### Environment:

* Specific purpleteam project and version? purpleteam@main
* Running locally or in the cloud? Locally
* Details of your specific System Under Test (SUT)?
* Which purpleteam components are running on which Operating System and version?
* Anything else that will set the stage for us understanding your context?

### Additional Details:
If the problem is universal then I can open a PR introducing the `dotenv` package and a sample.env file!

### Checklist

- [x] I have read the documentation.

**Comment by binarymist** [comment]
Why are you running it like that? Please follow the documentation.
