### ISSUE TITLE
Move hard coded timeouts in app.parallel.js of app-scanner to config

### ISSUE THREAD

**Issue by binarymist** [purpleteam-labs/purpleteam#15]
You could probably have a look at this one @ricekot? Get your bearings and propose the change?

**Comment by ricekot** [comment]
Sure.

**Comment by binarymist** [comment]
Currently being worked on as part of #60.

**Comment by binarymist** [comment]
Addressed in https://github.com/purpleteam-labs/purpleteam-app-scanner/releases/tag/v1.0.0-alpha.3
