### ISSUE TITLE
Unclear instructions / failing start

### ISSUE THREAD

**Issue by darkspirit510** [purpleteam-labs/purpleteam#79]
### Actual Behavior:

Wanted to try out purpleteam (guide at https://purpleteam-labs.com/doc/local/set-up/)

Cloned https://github.com/purpleteam-labs/purpleteam-orchestrator
`npm run dc-build`
results in
```
npm run dc-build                                                    

> purpleteam-orchestrator@0.1.1-alpha.1 dc-build /Users/my-user/Develop/purpleteam-orchestrator
> npm run dc-orchestrator-testers build


> purpleteam-orchestrator@0.1.1-alpha.1 dc-orchestrator-testers /Users/my-user/Develop/purpleteam-orchestrator
> APP_SCANNER_GROUP_ID=$(id -g) APP_SCANNER_USER_ID=$(id -u) ORCHESTRATOR_GROUP_ID=$(id -g) ORCHESTRATOR_USER_ID=$(id -u) docker-compose -f ./compose/orchestrator-testers-compose.yml "build"

WARNING: The HOST_DIR variable is not set. Defaulting to a blank string.
ERROR: build path /Users/my-user/develop/purpleteam-app-scanner either does not exist, is not accessible, or is not a valid URL.
```

Mh, okay. Can't see that in instructions, but okay. Cloned https://github.com/purpleteam-labs/purpleteam-app-scanner.
`npm run dc-build`
now results in
```
npm run dc-up

> purpleteam-orchestrator@0.1.1-alpha.1 dc-up /Users/my-user/Develop/purpleteam-orchestrator
> npm run dc-orchestrator-testers up


> purpleteam-orchestrator@0.1.1-alpha.1 dc-orchestrator-testers /Users/my-user/Develop/purpleteam-orchestrator
> APP_SCANNER_GROUP_ID=$(id -g) APP_SCANNER_USER_ID=$(id -u) ORCHESTRATOR_GROUP_ID=$(id -g) ORCHESTRATOR_USER_ID=$(id -u) docker-compose -f ./compose/orchestrator-testers-compose.yml "up"

WARNING: The HOST_DIR variable is not set. Defaulting to a blank string.
Creating network "compose_pt-net" with the default driver
Pulling redis (redis:alpine)...
alpine: Pulling from library/redis
540db60ca938: Pull complete
29712d301e8c: Pull complete
8173c12df40f: Pull complete
a77b7ddf4978: Pull complete
3f34a000c6b3: Pull complete
275dfaedaf41: Pull complete
Digest: sha256:f8f0e809a4281714c33edf86f6da6cc2d4058c8549e44d8c83303c28b3123072
Status: Downloaded newer image for redis:alpine
Creating compose_redis_1 ... done
Creating pt-app-scanner-cont  ... error
Creating pt-orchestrator-cont ... 

Creating pt-orchestrator-cont ... error

ERROR: for pt-orchestrator-cont  Cannot create container for service orchestrator: invalid mount config for type "bind": field Source must not be empty

ERROR: for app-scanner  Cannot create container for service app-scanner: invalid mount config for type "bind": field Source must not be empty

ERROR: for orchestrator  Cannot create container for service orchestrator: invalid mount config for type "bind": field Source must not be empty
ERROR: Encountered errors while bringing up the project.
```

...

### Expected Behavior:

Either something starts without error or guide has clear instructions.

...

### Steps to Reproduce:

Seen above.

...

### Environment:

* Specific purpleteam project and version?
0.1.1 (i guess)
* Running locally or in the cloud?
local
* Details of your specific System Under Test (SUT)?
didn't come there
* Which purpleteam components are running on which Operating System and version?
0.1.1
MacOS 11.4 + Docker 20.10.2
Ubuntu Server 20.04 + Docker 20.10.6
* Anything else that will set the stage for us understanding your context?
node v14.17.0

### Checklist

- [x] I have read the documentation. (I hope I did not oversee/misunderstand something)

**Comment by binarymist** [comment]
Hi @darkspirit510 

Did you read and follow the [directions](https://purpleteam-labs.com/doc/local/set-up/#environment-variables) around setting the `HOST_DIR`?

Also don't expect things to run until you've been right through the Set-up page and the links to the varius components (that you'll need to follow) to configure.

Once you're on the Workflow page (you've configured everything), things should run as expected.

I'll make some tweaks to the doc, hopefully it'll make it a bit clearer, if not, please let us know.

**Comment by binarymist** [comment]
Added following tweak to the doc: https://gitlab.com/purpleteam-labs/purpleteam-labs-web/-/commit/172ab380c802fedc0ec050e9119c7768734245af

**Comment by binarymist** [comment]
Closing due to lack of response.
