### ISSUE TITLE
broken link on the docker page 

### ISSUE THREAD

**Issue by shubhangi013** [purpleteam-labs/purpleteam#96]
The defect may already be reported! Please search for the defect before creating one.

### Actual Behavior:
The link in `BinaryMistSite Dockerfile ` on  `https://purpleteam-labs.com/doc/local/docker/#that-we-have-built` redirects to a page with 404 error.
![Screenshot from 2021-09-21 15-24-25](https://user-images.githubusercontent.com/78342516/134152479-34a570a8-9960-4835-8bcc-3cf7b95f6b7f.png)

...

### Expected Behavior:
The link in `BinaryMistSite Dockerfile ` on  `https://purpleteam-labs.com/doc/local/docker/#that-we-have-built` should re-direct to a GitLab page apparently.
...

### Steps to Reproduce:
Go to : https://purpleteam-labs.com/doc/local/docker/#that-we-have-built
click on DockerFile before BinaryMist

...

### Environment:

* Specific purpleteam project and version?
* Running locally or in the cloud?
* Details of your specific System Under Test (SUT)?
* Which purpleteam components are running on which Operating System and version?
* Anything else that will set the stage for us understanding your context?

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, Github Discussions, links for us to have context, eg. code from your repository, a discussion in stackoverflow, gitter, etc)

### Checklist

- [X] I have read the documentation.

**Comment by binarymist** [comment]
Thanks @shubhangi013 . Have removed those links.
